name: CI

on:
  push:
    branches: [main, feat/*]
  pull_request:
    branches: [main, feat/*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Lint
        run: npm run lint
        continue-on-error: false
